# Generated by Django 4.1.5 on 2023-01-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='URL',
        ),
        migrations.AddField(
            model_name='product',
            name='href',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
