# Generated by Django 4.1.5 on 2023-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_url_product_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='href',
            field=models.URLField(),
        ),
    ]
