# Generated by Django 4.1.5 on 2023-01-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_url_product_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(max_length=10000)),
            ],
        ),
    ]
