# Generated by Django 4.1.5 on 2023-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_idobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_status',
            field=models.CharField(default='n/a', max_length=30),
        ),
    ]
