# Generated by Django 4.1.5 on 2023-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_status',
            field=models.BooleanField(),
        ),
    ]
