# Generated by Django 4.1.5 on 2023-01-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_product_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='n/a', max_length=50, null=True),
        ),
    ]
