# Generated by Django 4.1.5 on 2023-01-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_idstring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdObject',
        ),
    ]
