# Generated by Django 4.1.5 on 2023-01-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_sell_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_status',
            field=models.CharField(default='no data', max_length=30),
        ),
    ]
