# Generated by Django 4.1.5 on 2023-01-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
