# Generated by Django 4.1.5 on 2023-01-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_usercart_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='internal_item_id',
            field=models.IntegerField(),
        ),
    ]
