# Generated by Django 4.1.5 on 2023-01-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_usercart_internal_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
