# Generated by Django 4.1.5 on 2023-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='item_qty',
            field=models.IntegerField(default=1),
        ),
    ]
